### ISSUE TITLE
Unexpected Freeze on asset compilation

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [smokeelow/intellij-sfcc#42]
Dear @smokeelow, many thx for this super helpfull plugin. In the recent version for 2023.2 together with webstorm 2023.2 I get strange freezes of the system on asset compliation.

We have a grunt process compiling scss files into css (a lot) and either the SFCC plugins upload crashed with teh WebStorm indexing prcess or wise versa. If I change any scss file, the whole programm freezes which is unworkable.

I tried already to move the compilation watch process into a seperate terminal (independend of webstorm), but it does not help.

Unfortunatly I can not provide more informatin, but if you guide me through, I'm happy to provide any debug information possible.

Thx a lot!
Andreas

**Comment by smokeelow** [comment]
hi @Andreas-Schoenefeldt , yeah this is regression issue in the IDE, I've filed a bug and it was fixed partially (freeze is gone now in `2023.2.1`)

Root cause: very long CSS selectors generated by bundle systems like `webpack` etc.

See https://youtrack.jetbrains.com/issue/WEB-62040/Extremely-long-CSS-selector-list-causes-IDE-freeze-in-2023.2-too-long-CSS-lexing

**Comment by smokeelow** [comment]
as a workaround you can add to ignore your main compiled css file or switch to `2023.2.1` release candidate/preview version

**Comment by Andreas-Schoenefeldt** [comment]
Thx a lot! 2023.2.1 works indeed much better.
